---
title: "Analyzing the evolution of plant vessel size in response to Freezing Temperatures"
output: html_notebook
---

First load the required packages and datasets. 

```{r}
library(devtools)
library(bayou)
library(treeplyr)
#library(pez)
library(caper)
library(dplyr)
#install_github("richfitz/phyndr")
#install_github("wcornwell/taxonlookup")
library(phyndr)
library(taxonlookup)
library(diversitree)
library(OUwie)
library(foreach)
library(doParallel)
library(iterators)
library(reshape2)

setwd("~/repos/growthforms/analysis/")
```

Match the resulting datasets and process them for analyses by setting up variables representing alternative hypotheses for the drivers of vessel size evolution. 

```{r}
## Read in trees, climate data, taxonomy and growth form data. 
tree <- read.tree("../datasets/zanne1.1.tre")
AEZ3 <- read.csv("../speciesTraitDataAEZ3.csv")
#climate <- read.csv("../WoodyClimateHemi.12May.csv")
species.summaries <- read.csv("../datasets/species_summaries+newquant.csv")
plant_lookup <- plant_lookup()

## Prepare names for matching
AEZ3$species <- gsub(" ", "_", AEZ3$gs)
#climate$species <- gsub(" ", "_", climate$species)
#dat.old <- left_join(climate, AEZ3)
#colnames(species.summaries)[1] <- "species"
#rownames(dat.old) <- dat.old$species
species.summaries$species <- gsub(" ", "_", species.summaries$species)
dat.new <- left_join(species.summaries, AEZ3)
rownames(dat.new) <- gsub(" ", "_", dat.new$species)

tax <- lookup_table(unique(c(tree$tip.label, rownames(dat.new))), by_species = TRUE)
tree.missing <- setdiff(tree$tip.label, rownames(tax))
dat.missing <- setdiff(rownames(dat.new), rownames(tax))
ptree <- drop.tip(tree, tree.missing)
#pdat <- rownames(dat.new)[-match(dat.missing, dat.new$species)]
nH <- nodeHeights(ptree)
ptree$edge.length[ptree$edge[,2] <= length(ptree$tip.label)] <- 
  ptree$edge.length[ptree$edge[,2] <= length(ptree$tip.label)] + (max(branching.times(ptree)) - nH[ptree$edge[,2] <= length(ptree$tip.label), 2])
is.ultrametric(ptree)

```

```{r}
tdOUwie <- make.treedata(ptree, dat.new) 
tdOUwie
```

```{r}
tdOUwie <- make.treedata(ptree, dat.new) 
tdOUwie <- filter(tdOUwie, !is.na(vesselSize), !is.na(phenology),!is.na(tmin.01))
tdOUwie <- dplyr::select(tdOUwie, vesselSize, phenology, starts_with("tmin"))
tdOUwie <- mutate(tdOUwie, OU2freeze.01 = c("NF", "F")[as.numeric(tmin.01 < 0)+1],
                            OU2freeze.025 = c("NF", "F")[as.numeric(tmin.025 < 0)+1],
                              OU2freeze.05 = c("NF", "F")[as.numeric(tmin.05 < 0)+1],
                                OU2freeze.50 = c("NF", "F")[as.numeric(tmin.50 < 0)+1],
                                  OU2freeze.95 = c("NF", "F")[as.numeric(tmin.95 < 0)+1], 
                                    OU2freeze.975 = c("NF", "F")[as.numeric(tmin.975 < 0)+1], 
                                      OU2freeze.99 = c("NF", "F")[as.numeric(tmin.99 < 0)+1], 
                                        OU2freeze.mean = c("NF", "F")[as.numeric(tmin.mean < 0)+1], 
                                          OU2freeze.lower = c("NF", "F")[as.numeric(tmin.lower < 0)+1],
                                            OU2freeze.upper = c("NF", "F")[as.numeric(tmin.upper < 0)+1])

pasteNA <- function(x, y, sep=" ", collapse=NULL){
  ifelse(is.na(y), NA, paste(x,y, sep=sep, collapse=collapse))
}

tdOUwie <- mutate(tdOUwie, OU1="global", OU2phenology=phenology, lnVs=log(vesselSize))
tdOUwie <- mutate(tdOUwie, OU4freeze.01= paste(phenology, OU2freeze.01, sep="_"), 
                            OU4freeze.025= paste(phenology, OU2freeze.025, sep="_"),
                              OU4freeze.05= paste(phenology, OU2freeze.05, sep="_"),
                                OU4freeze.50= paste(phenology, OU2freeze.50, sep="_"),
                                  OU4freeze.95= paste(phenology, OU2freeze.95, sep="_"),
                                    OU4freeze.975= paste(phenology, OU2freeze.975, sep="_"),
                                      OU4freeze.99= paste(phenology, OU2freeze.99, sep="_"),
                                        OU4freeze.mean= paste(phenology, OU2freeze.mean, sep="_"), 
                                          OU4freeze.lower = pasteNA(phenology, OU2freeze.lower, sep="_"),
                                            OU4freeze.upper = pasteNA(phenology, OU2freeze.upper, sep="_")
                  )
tdOUwie <- treeply(tdOUwie, reorder, "postorder")
tdOUwieFreeze <- dplyr::select(tdOUwie, lnVs, OU1, starts_with("OU"))
par(mfrow=c(5,4), mar=c(2, 2, 0.1, 0.1))
dum <- lapply(2:19, function(x) boxplot(tdOUwieFreeze[['lnVs']] ~ tdOUwieFreeze[[x]]))

```


Scale tree to unit height:

```{r}
tdOUwieFreeze$phy$edge.length <- tdOUwieFreeze$phy$edge.length/max(branching.times(tdOUwieFreeze$phy))
#tree <- tdOUwieFreeze$phy
#tree$edge.length <- tree$edge.length/max(branching.times(tree))
#dat <- tdOUwieFreeze$dat
```

```{r}
require(foreach)
require(doParallel)
registerDoParallel(cores=8)
itd <- iter(tdOUwieFreeze$dat[,3:ncol(tdOUwieFreeze$dat)], by="column")
smtds <- foreach(i=itd) %do% {
  idat <- data.frame(tdOUwieFreeze$phy$tip.label, "lnVs"=tdOUwieFreeze$dat$lnVs,i)
  itdx <- make.treedata(tdOUwieFreeze$phy, idat) 
  itdx <- filter(itdx, !is.na(itdx$dat[[2]]))
}

#smtrees.ER <- foreach(i=itd) %dopar% {
#  idat <- cbind(tdOUwieFreeze$phy$tip.label, i)
#  itdx <- make.treedata(tdOUwieFreeze$phy, idat) 
#  itdx <- filter(itdx, !is.na(itdx$dat[[1]]))
#  make.simmap(itdx$phy, itdx[[1]], model="ER", nsim=20)
#}

#saveRDS(smtrees, file="../output/smtrees_ER.rds")
smtrees.ER <- readRDS("../output/smtrees_ER.rds")
```


```{r}
tree <- tdOUwieFreeze$phy
dat <- tdOUwieFreeze$dat

registerDoParallel(cores = 5)

ouwie.dat <- data.frame('Genus_species' = tree$tip.label, 'Reg' = dat[[2]], 'X' = dat$lnVs, "MEerr" = 0.02)
#BM.fit <- OUwie(tree, ouwie.dat, model="BM1", mserr="known")
#OU1.fit <- OUwie(tree, ouwie.dat, model="OU1", mserr="known")
#saveRDS(BM.fit, "../output/BMfit.rds")
#saveRDS(OU1.fit, "../output/OUfit.rds")
BM.fit <- readRDS("../output/OUwie/BMfit.rds")
OU1.fit <- readRDS("../output/OUwie/OUfit.rds")

classPhylo <- function(tree){
  class(tree) <- "phylo"
  tree
}

#stree.dat <- lapply(3:ncol(tdOUwieFreeze$dat), function(i) make.treedata((idat = tdOUwieFreeze$dat[[i]], itree = smtrees.ER[[i-2]])))
ouwie.dats <- lapply(3:ncol(tdOUwieFreeze$dat), function(i) data.frame('Genus_species'=tdOUwieFreeze$phy$tip.label, "Reg"=tdOUwieFreeze[[i]], "X"=tdOUwieFreeze[['lnVs']], "MEerr"=0.02))
ouwie.tds <- lapply(1:length(ouwie.dats), function(i) lapply(smtrees.ER[[i]], function(tr)  make.treedata(classPhylo(tr), ouwie.dats[[i]]) %>% filter(., !is.na(Reg)) ))

itd <- iter(ouwie.tds[1:19])

#  idat <- cbind(tdOUwieFreeze$phy$tip.label, i)
#  itdx <- make.treedata(tdOUwieFreeze$phy, idat) 
#  itdx <- filter(itdx, !is.na(itdx$dat[[1]]))

itd <- iter(ouwie.tds[1:19])
OUM.fits <- foreach(x=itd) %dopar% {
  lapply(x, function(tdx) OUwie(tdx$phy, as.data.frame(tdx$dat), model="OUM", mserr="known", simmap.tree = TRUE))
}
saveRDS(OUM.fits, file="../output/OUwie/OUMfits.rds")

itd <- iter(ouwie.tds[1:19])
OUMA.fits <- foreach(x=itd) %dopar% {
  lapply(x, function(tdx) OUwie(tdx$phy, as.data.frame(tdx$dat), model="OUMA", mserr="known", simmap.tree = TRUE))
}
saveRDS(OUMA.fits, file="../output/OUwie/OUMAfits.rds")

itd <- iter(ouwie.tds[1:19])
OUMV.fits <- foreach(x=itd) %dopar% {
  lapply(x, function(tdx) OUwie(tdx$phy, as.data.frame(tdx$dat), model="OUMV", mserr="known", simmap.tree = TRUE))
}
saveRDS(OUMV.fits, file="../output/OUwie/OUMVfits.rds")

itd <- iter(ouwie.tds[1:19])
BMS.fits <- foreach(x=itd) %dopar% {
  lapply(x, function(tdx) OUwie(tdx$phy, as.data.frame(tdx$dat), model="BMS", mserr="known", simmap.tree = TRUE))
}
saveRDS(BMS.fits, file="../output/OUwie/BMSfits.rds")

## Added upper/lower so rerunning with just those:

itd <- iter(ouwie.tds[20:21])
OUM.fits2 <- foreach(x=itd) %dopar% {
  lapply(x, function(tdx) OUwie(tdx$phy, as.data.frame(tdx$dat), model="OUM", mserr="known", simmap.tree = TRUE))
}
saveRDS(OUM.fits2, file="../output/OUwie/OUMfits2.rds")

itd <- iter(ouwie.tds[20:21])
OUMA.fits2 <- foreach(x=itd) %dopar% {
  lapply(x, function(tdx) OUwie(tdx$phy, as.data.frame(tdx$dat), model="OUMA", mserr="known", simmap.tree = TRUE))
}
saveRDS(OUMA.fits2, file="../output/OUwie/OUMAfits2.rds")

itd <- iter(ouwie.tds[20:21])
OUMV.fits2 <- foreach(x=itd) %dopar% {
  lapply(x, function(tdx) OUwie(tdx$phy, as.data.frame(tdx$dat), model="OUMV", mserr="known", simmap.tree = TRUE))
}
saveRDS(OUMV.fits2, file="../output/OUwie/OUMVfits2.rds")

itd <- iter(ouwie.tds[20:21])
BMS.fits2 <- foreach(x=itd) %dopar% {
  lapply(x, function(tdx) OUwie(tdx$phy, as.data.frame(tdx$dat), model="BMS", mserr="known", simmap.tree = TRUE))
}
saveRDS(BMS.fits2, file="../output/OUwie/BMSfits2.rds")

```


```{r}
BM.fit <- readRDS("../output/OUwie/BMfit.rds")
OU1.fit <- readRDS("../output/OUwie/OUfit.rds")
OUM.fits <- readRDS("../output/OUwie/OUMfits.rds")
OUMA.fits <- readRDS("../output/OUwie/OUMAfits.rds")
#OUMV.fits <- readRDS("../output/OUwie/OUMVfits.rds")
OUMV.fits <- readRDS("../output/OUwie/cleanOUMVfits.rds")
BMS.fits <- readRDS("../output/OUwie/BMSfits.rds")

## This will be combined later, but since we ran in parts:
OUM.fits2 <- readRDS("../output/OUwie/OUMfits2.rds")
OUMA.fits2 <- readRDS("../output/OUwie/OUMAfits2.rds")
OUMV.fits2 <- readRDS("../output/OUwie/OUMVfits2.rds")
BMS.fits2 <- readRDS("../output/OUwie/BMSfits2.rds")


```

Some functions to handle the lists of lists of results.

```{r}
reshapeFx <- function(i, fits) do.call(rbind, lapply(1:length(fits[[i]]), function(x) cbind("replicate"=x, melt(rbind(fits[[i]][[x]]$solution, fits[[i]][[x]]$solution[2,]/(2*fits[[i]][[x]]$solution[1,])) ))))
aicFx <- function(i, fits) do.call(rbind, lapply(1:length(fits[[i]]), function(x) cbind("replicate"=x, "aic"=fits[[i]][[x]]$AICc)))
reshapeBMFx <- function(i, fits) do.call(rbind, lapply(1:length(fits[[i]]), function(x) cbind("replicate"=x, melt(rbind(fits[[i]][[x]]$solution)))))

getOUSummaryFits <- function(fits){
  AICcs <- do.call(rbind, lapply(1:length(fits), function(x) data.frame("data"=colnames(dat)[x+2], aicFx(x, fits))))
  solutions <- do.call(rbind, lapply(1:length(fits), function(x) cbind("data"=colnames(dat)[x+2], reshapeFx(x, fits))))
  solutions$Var1 <- as.character(solutions$Var1)
  return(list(AICc = AICcs, solutions=solutions))
}
getBMSummaryFits <- function(fits){
  AICcs <- do.call(rbind, lapply(1:length(fits), function(x) data.frame("data"=colnames(dat)[x+2], aicFx(x, fits))))
  solutions <- do.call(rbind, lapply(1:length(fits), function(x) cbind("data"=colnames(dat)[x+2], reshapeBMFx(x, fits))))
  solutions$Var1 <- as.character(solutions$Var1)
  solutions$Var1[solutions$Var1==""] <- "Vy"
  return(list(AICc = AICcs, solutions=solutions))
}

```


```{r}
dat <- tdOUwieFreeze$dat
dat <- dat[,which(!colnames(dat) %in% c("OU2freeze.lower", "OU2freeze.upper", "OU4freeze.lower", "OU4freeze.upper"))]

OU1.summary <- getOUSummaryFits(list(list(OU1.fit)))
BM.summary <- getBMSummaryFits(list(list(BM.fit)))
OUMV.summary <- getOUSummaryFits(OUMV.fits)
OUM.summary <- getOUSummaryFits(OUM.fits)
OUMA.summary <- getOUSummaryFits(OUMA.fits)
BMS.summary <- getBMSummaryFits(BMS.fits)
OUMA.summary$AICc$aic[OUMA.summary$AICc$aic < 500] <- NA

OU1.summary
BM.summary
OUMV.summary
OUM.summary
OUMA.summary
BMS.summary

```

Extract theta values
```{r}
OUM.theta <- lapply(1:length(OUM.fits), function(x) do.call(rbind, lapply(1:length(OUM.fits[[x]]), function(y) {z <- OUM.fits[[x]][[y]]$theta; rownames(z) <- paste(rep(x, nrow(z)),y, sep=".");z <- as.data.frame(z);z <- cbind("reg"=as.character(OUM.fits[[x]][[y]]$tot.states), z); z})))

OUMV.theta <- lapply(1:length(OUMV.fits), function(x) do.call(rbind, lapply(1:length(OUMV.fits[[x]]), function(y) {z <- OUMV.fits[[x]][[y]]$theta; rownames(z) <- paste(rep(x, nrow(z)),y, sep=".");z <- as.data.frame(z);z <- cbind("reg"=as.character(OUMV.fits[[x]][[y]]$tot.states), z); z})))

OUMA.theta <- lapply(1:length(OUMA.fits), function(x) do.call(rbind, lapply(1:length(OUMA.fits[[x]]), function(y) {z <- OUMA.fits[[x]][[y]]$theta; rownames(z) <- paste(rep(x, nrow(z)),y, sep=".");z <- as.data.frame(z);z <- cbind("reg"=as.character(OUMA.fits[[x]][[y]]$tot.states), z); z})))

```

```{r}
#Compile all AICcs
AICcs <- data.frame(Model=c("BM1","OU1"), data=rep(NA,2), replicate=sort(rep(1:10,2)), aic=c(BM.fit$AICc, OU1.fit$AICc))
tmp <- do.call(rbind, list(cbind(Model="OUM", OUM.summary$AICc),
                    cbind(Model="OUMV", OUMV.summary$AICc),
                    cbind(Model="OUMA", OUMA.summary$AICc),
                    cbind(Model="BMS", BMS.summary$AICc)))
AICcs <- as.data.frame(rbind(AICcs, tmp))

AICcs <- do.call(rbind, lapply(1:10, function(x){
  filter(AICcs, replicate==x, !data %in% c("OU2freeze.lower", "OU2freeze.upper", "OU4freeze.upper", "OU4freeze.lower")) %>% mutate(., "dAIC" = aic-min(aic, na.rm=TRUE))
}))

group_by(AICcs, data, Model) %>% summarize(., mean.dAIC = mean(dAIC, na.rm=TRUE), best.Model = sum(dAIC[!is.na(dAIC)]<2), sd.dAIC=sd(dAIC, na.rm=TRUE)) %>% arrange(., mean.dAIC)

```



```{r}
par(mar=c(10, 2, 4,0), mfrow=c(1,4))


boxplot(OUM.summary$AICc$aic~OUM.summary$AICc$data, las=2, ylim=c(1100, 1700), main="OUM")
abline(h=OU1.fit$AICc, col="red", lty=2, lwd=2)
abline(h=seq(1000, 2000, 50), lty=2)
boxplot(OUMV.summary$AICc$aic~OUMV.summary$AICc$data, las=2, ylim=c(1100, 1700), col=bayou:::makeTransparent("red", alpha=50), main="OUMV")
abline(h=seq(1000, 2000, 50), lty=2)
boxplot(OUMA.summary$AICc$aic~OUMA.summary$AICc$data, las=2, ylim=c(1100, 1700), col=bayou:::makeTransparent("green", alpha=50), main="OUMA")
abline(h=seq(1000, 2000, 50), lty=2)
boxplot(BMS.summary$AICc$aic~BMS.summary$AICc$data, las=2, ylim=c(1100, 1700), col=bayou:::makeTransparent("blue", alpha=50), main="BMS")
abline(h=seq(1000, 2000, 50), lty=2)
abline(h=BM.fit$AICc, col="red", lty=2, lwd=2)

par(mfrow=c(1,1), mar=c(5,4,4,2))
boxplot(OUM.theta[[10]]$V1~OUM.theta[[10]]$reg, main="OUM4freeze.01", ylab="theta")
boxplot(OUM.theta[[11]]$V1~OUM.theta[[11]]$reg, main="OUM4freeze.025", ylab="theta")


```
